// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TransitDataUT
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class TransitDataAdapterFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TransitDataAdapter.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "TransitDataAdapter", "\t為提供資料傳遞過程採用中介資料傳遞，\r\n\t操作及使用時採用資料物件，\r\n\t提供資料物件轉換為中介資料及從中介資料載入為資料物件的轉換器功能。", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "TransitDataAdapter")))
            {
                global::TransitDataUT.TransitDataAdapterFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("轉換 Employee 資料物件為字串中介資料")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TransitDataAdapter")]
        public virtual void 轉換Employee資料物件為字串中介資料()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("轉換 Employee 資料物件為字串中介資料", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Level",
                        "Title"});
            table1.AddRow(new string[] {
                        "Tomozou Huang",
                        "1",
                        "Staff"});
#line 7
 testRunner.Given("僱員資料", ((string)(null)), table1, "Given ");
#line 10
 testRunner.When("要求轉換為字串中介資料", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
 testRunner.Then("得到字串中介資料", @"<Root>
  <Name>Tomozou Huang</Name>
  <Level>1</Level>
  <Title>Staff</Title>
  <TEL Type=""String"">
	<Item>abc</Item>
	<Item>def</Item>
  </TEL>
  <ToDoList Type=""System.Xml.Linq.XElement"">
	<Item><![CDATA[<Root>
  <Title>ToDo1</Title>
  <Description>Do Something.</Description>
</Root>]]></Item>
	<Item><![CDATA[<Root>
  <Title>2</Title>
  <Description>Do Something 2</Description>
</Root>]]></Item>
  </ToDoList>
</Root>", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("轉字串中介資料為 Employee 資料物件")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TransitDataAdapter")]
        public virtual void 轉字串中介資料為Employee資料物件()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("轉字串中介資料為 Employee 資料物件", ((string[])(null)));
#line 34
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 35
 testRunner.Given("字串中介資料", "<Root>\r\n\t<Name>Tomozou Huang</Name>\r\n\t<Level>1</Level>\r\n\t<Title>Staff</Title>\t\t\r\n" +
                    "</Root>", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
 testRunner.When("要求轉換為 Employee 資料物件", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Level",
                        "Title"});
            table2.AddRow(new string[] {
                        "Tomozou Huang",
                        "1",
                        "Staff"});
#line 44
 testRunner.Then("得到 Employee 資料物件", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("轉字串清單資料物件")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "TransitDataAdapter")]
        public virtual void 轉字串清單資料物件()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("轉字串清單資料物件", ((string[])(null)));
#line 48
this.ScenarioSetup(scenarioInfo);
#line hidden
#line 49
 testRunner.Given("字串中介資料", "<Root>\t\t\t\r\n\t<TEL Type=\"System.String\">\r\n\t\t<Item>abc</Item>\r\n\t\t<Item>def</Item>\r\n\t" +
                    "</TEL>\r\n</Root>", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
 testRunner.When("要求轉換為 Employee 資料物件", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "TEL"});
            table3.AddRow(new string[] {
                        "abc"});
            table3.AddRow(new string[] {
                        "def"});
#line 59
 testRunner.Then("得到 Employee 資料物件包含電話清單", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
